### ISSUE TITLE
Chat GPT not working 

### ISSUE THREAD

**Issue by niiccoo2** [niiccoo2/NDX#17]
How to recreate:
Start NDX,
Press 8 for ChatGPT,
Enter the password (dumb123),
Type anything.

Error:
Traceback (most recent call last):
  File "main.py", line 100, in <module>
    chatGPT()
  File "/home/runner/NDX/chatGPT.py", line 21, in chatGPT
    chat = openai.ChatCompletion.create(
  File "/home/runner/NDX/venv/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/runner/NDX/venv/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/runner/NDX/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 230, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/runner/NDX/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 624, in _interpret_response
    self._interpret_response_line(
  File "/home/runner/NDX/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 687, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: <empty message>

**Comment by niiccoo2** [comment]
How to recreate:
Start NDX,
Press 8 for ChatGPT,
Enter the password (dumb123),
Type anything.

Error:
Traceback (most recent call last):
  File "main.py", line 100, in <module>
    chatGPT()
  File "/home/runner/NDX/chatGPT.py", line 21, in chatGPT
    chat = openai.ChatCompletion.create(
  File "/home/runner/NDX/venv/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/runner/NDX/venv/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/runner/NDX/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 230, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/runner/NDX/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 624, in _interpret_response
    self._interpret_response_line(
  File "/home/runner/NDX/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 687, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: <empty message>

**Comment by niiccoo2** [comment]
I added a thing saying that it is not working this time so if you want to test it you have to remove that and uncomment the password part in main.py
